server:
  port: 8080

spring:
#  profiles:
#    active: develop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipedb
    username: pgUser
    password: pgPassword
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:/db/migration/
    validate-on-migrate: true
    baseline-on-migrate: true
