/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gmail.gremlin.gosha.recipe.backend;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RecipeApplication {

  public static void main(String[] args) {
    SpringApplication.run(RecipeApplication.class, args);
  }

}
