/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.gmail.gremlin.gosha

import com.gmail.gremlin.gosha.recipe.backend.AccountController
import com.gmail.gremlin.gosha.recipe.backend.AccountDto
import spock.lang.Specification
import spock.lang.Unroll

class AccountControllerTest extends Specification {

    private AccountController controller;

    @Unroll
    def "getAccountById verify returns right account"() {
        setup:
        def controller = new AccountController()

        when:
        AccountDto result = controller.getAccountById(id)

        then:
        result.getId() == id
        result.getName() == name

        where:
        id | name
        1L | 'name1'
        2L | 'name2'
        3L | 'name3'
        4L | 'name4'
    }

    def "getAccountById verify exception when id is not positive"() {
        setup:
        def controller = new AccountController()

        when:
        controller.getAccountById(-1L)

        then:
        thrown(RuntimeException.class)
    }
}
